[package]
name = "tsp_art"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
image = "0.25.5"
rand = "0.9.0"
svg = "0.18.0"
voronator = "0.2.1"
rayon = "1.7"
geo = "0.29.3"
kdtree = "0.7.0"
